import type { Plugin, TAbstractFile } from 'obsidian'
import { App, Notice, TFile, TFolder, normalizePath } from 'obsidian'
import {
  type PMSettings,
  type Project,
  type ProjectPatch,
  type ResolvedProjectConfig,
  type StatusConfig,
  type Task,
  DEFAULT_SETTINGS,
  makeProject,
  makeTask,
  today,
  isTerminalStatus,
  sanitizeFileName,
  resolveProjectConfig,
  computeSchedule,
  findParentId,
  findTaskById,
  indexAddSubtree,
  indexRemoveSubtree,
  indexSetParent,
  rebuildTaskIndex,
  addTaskToTree,
  cloneTaskSubtree,
  deleteTaskFromTree,
  flattenTasks,
  moveTaskInTree,
  updateTaskInTree,
  hydrateProjectFromFrontmatter,
  hydrateTaskFromFile,
  customFieldList,
  type CustomFieldDef,
  FRONTMATTER_KEY,
  TASK_FRONTMATTER_KEY,
  parseFrontmatter,
  stripAutoGeneratedContent,
  buildTaskFrontmatter,
  foreignFrontmatter,
  PROJECT_FRONTMATTER_KEYS,
  serializeProject,
  serializeTask,
  TASK_FRONTMATTER_KEYS,
  taskFilePath,
  TASK_SLUG_MAX_LENGTH,
  type RefWriter
} from '@system-commons/core'
import { archiveTask as doArchiveTask, unarchiveTask as doUnarchiveTask } from './ArchiveOps'
import type { VaultIndex } from './VaultIndex'
import { refLink, refListToIds, refToId } from './refs'
import {
  ensureFolder,
  folderOf,
  keepProjectStorageWithNote,
  moveTaskAttachmentFolder,
  projectTaskFolder,
  projectFilePath
} from './vaultFs'
import type { ImportNoteOptions, TaskSource } from './TaskSource'

/** 'fm' writes via processFrontMatter; 'full' rewrites the body too, via vault.process. */
type DirtyKind = 'fm' | 'full'

function patchNeedsBodyRewrite(patch: Partial<Task>): boolean {
  // `subtasks` changes the parent's `## Subtasks` list, which lives in the body.
  return patch.description !== undefined || patch.archived !== undefined || patch.subtasks !== undefined
}

export class TaskFileNameConflictError extends Error {
  constructor(public readonly path: string) {
    super(`A note named "${fileNameFromPath(path)}" already exists.`)
    this.name = 'TaskFileNameConflictError'
  }

  get fileName(): string {
    return fileNameFromPath(this.path)
  }
}

function fileNameFromPath(path: string): string {
  return path.slice(path.lastIndexOf('/') + 1).replace(/\.md$/, '')
}

/**
 * All read/write operations against the vault. The project note holds its metadata and
 * the `_tasks/` folder beside it holds one file per task. The in-memory `Project.tasks`
 * tree is assembled from those files on load.
 */
export class ProjectStore implements TaskSource {
  private saveQueues = new Map<string, Promise<void>>()

  /** Task IDs needing a write on the next save. Tasks with no filePath are always 'full'. */
  private dirtyTasks = new Map<string, Map<string, DirtyKind>>()

  /**
   * Objects whose in-memory `description` is known to match disk. Cache-loaded ones
   * start out absent: their description is empty until loadTaskBody / loadProjectBody
   * fills it, or a 'full' save reads it back inline.
   */
  private hydratedBodies = new WeakSet<Task | Project>()

  /**
   * The one live Project per path, held as the loading promise so concurrent loads
   * collapse onto a single instance. Mutators and reloads update that object in
   * place; it is replaced only when the project is deleted.
   */
  private projectCache = new Map<string, Promise<Project | null>>()

  private changeHandlers = new Set<(path: string) => void>()

  private reloadTimers = new Map<string, number>()
  private static readonly RELOAD_DEBOUNCE_MS = 300

  /** Paths we wrote ourselves, timestamped, so vault listeners can ignore the echo. */
  private selfWrites = new Map<string, number>()
  private static readonly SELF_WRITE_WINDOW_MS = 5000

  constructor(
    private app: App,
    private getSettings: () => PMSettings = () => DEFAULT_SETTINGS,
    /** Absent in tests and before the layout is ready. */
    private index?: VaultIndex,
    /** Writes the settings back after a load folds something into them. */
    private persistSettings?: () => Promise<void>
  ) {}

  configFor(project: Project): ResolvedProjectConfig {
    return resolveProjectConfig(project, this.getSettings())
  }

  private statusesFor(project: Project): StatusConfig[] {
    return this.configFor(project).statuses
  }

  /** Bound to the note being written: how far a link abbreviates depends on where it sits. */
  private refsFor(project: Project, sourcePath: string): RefWriter {
    const link = (targetPath: string, title: string): string => refLink(this.app, targetPath, title, sourcePath)
    return {
      link,
      dependency: (taskId) => {
        const local = findTaskById(project, taskId)
        return local?.filePath ? link(local.filePath, local.title) : null
      }
    }
  }

  private markDirty(project: Project, taskIds: Iterable<string>, kind: DirtyKind): void {
    let map = this.dirtyTasks.get(project.filePath)
    if (!map) {
      map = new Map()
      this.dirtyTasks.set(project.filePath, map)
    }
    for (const id of taskIds) {
      // Upgrade-only: 'full' wins over 'fm', never the reverse.
      if (map.get(id) === 'full') continue
      map.set(id, kind)
    }
  }

  private markSubtreeDirty(project: Project, taskId: string, kind: DirtyKind): void {
    const task = findTaskById(project, taskId)
    if (!task) return
    this.markDirty(project, [taskId], kind)
    for (const ft of flattenTasks(task.subtasks)) {
      this.markDirty(project, [ft.task.id], kind)
    }
  }

  private markAllDirty(project: Project, kind: DirtyKind): void {
    const ids: string[] = []
    for (const ft of flattenTasks(project.tasks)) ids.push(ft.task.id)
    this.markDirty(project, ids, kind)
  }

  private clearDirty(project: Project): void {
    this.dirtyTasks.delete(project.filePath)
  }

  private markSelfWrite(path: string): void {
    if (this.selfWrites.size > 256) {
      const cutoff = Date.now() - ProjectStore.SELF_WRITE_WINDOW_MS
      for (const [p, t] of this.selfWrites) {
        if (t < cutoff) this.selfWrites.delete(p)
      }
    }
    this.selfWrites.set(path, Date.now())
  }

  private peekSelfWrite(path: string): boolean {
    const ts = this.selfWrites.get(path)
    return ts !== undefined && Date.now() - ts < ProjectStore.SELF_WRITE_WINDOW_MS
  }

  /** Returns the unsubscribe function. */
  onProjectChanged(handler: (path: string) => void): () => void {
    this.changeHandlers.add(handler)
    return () => this.changeHandlers.delete(handler)
  }

  private emitChange(path: string): void {
    for (const handler of this.changeHandlers) handler(path)
  }

  /** Call once from onload. The only place the plugin listens for project file changes. */
  registerVaultSync(plugin: Plugin): void {
    const onChange = (file: TAbstractFile): void => this.syncPath(file.path)
    plugin.registerEvent(this.app.vault.on('create', onChange))
    plugin.registerEvent(this.app.vault.on('modify', onChange))
    plugin.registerEvent(this.app.vault.on('delete', onChange))
    plugin.registerEvent(
      this.app.vault.on('rename', (file, oldPath) => {
        // Obsidian is still finishing this rename, and moving files while it does blocks
        // it, so the follow-up waits for the current one to settle.
        if (file instanceof TFile) {
          window.setTimeout(() => {
            void this.followProjectRename(oldPath, file.path)
          }, 0)
        }
        this.syncPath(file.path)
        this.syncPath(oldPath)
      })
    )
    plugin.register(() => {
      for (const timer of this.reloadTimers.values()) window.clearTimeout(timer)
      this.reloadTimers.clear()
    })
  }

  /** A renamed project note takes its folder, or failing that its task folder, with it. */
  private async followProjectRename(oldPath: string, newPath: string): Promise<void> {
    if (!this.projectCache.has(oldPath) && !this.isProjectNote(newPath)) return
    try {
      const notePath = await keepProjectStorageWithNote(this.app, oldPath, newPath, (p) => this.markSelfWrite(p))
      await this.rekeyProject(oldPath, notePath)
    } catch (e) {
      console.error(`[PM] Failed to move the task folder for "${newPath}":`, e)
    }
  }

  private isProjectNote(path: string): boolean {
    const file = this.app.vault.getAbstractFileByPath(path)
    if (!(file instanceof TFile)) return false
    return this.app.metadataCache.getFileCache(file)?.frontmatter?.[FRONTMATTER_KEY] === true
  }

  /** Moves the live project, its queue and its pending writes onto the note's new path. */
  private async rekeyProject(oldPath: string, newPath: string): Promise<void> {
    if (oldPath === newPath) return
    const cached = this.projectCache.get(oldPath)
    if (!cached) return
    this.projectCache.delete(oldPath)
    this.projectCache.set(newPath, cached)
    const dirty = this.dirtyTasks.get(oldPath)
    if (dirty) {
      this.dirtyTasks.delete(oldPath)
      this.dirtyTasks.set(newPath, dirty)
    }
    const queued = this.saveQueues.get(oldPath)
    if (queued) {
      this.saveQueues.delete(oldPath)
      this.saveQueues.set(newPath, queued)
    }
    const project = await cached
    if (!project) return
    project.filePath = newPath
    this.emitChange(newPath)
  }

  /** An external write landed: reload the live project so every holder sees it. */
  private syncPath(path: string): void {
    if (this.projectCache.size === 0) return
    if (this.peekSelfWrite(path)) return
    for (const key of this.projectCache.keys()) {
      if (path === key || path.startsWith(projectTaskFolder(key) + '/')) {
        const pending = this.reloadTimers.get(key)
        if (pending !== undefined) window.clearTimeout(pending)
        this.reloadTimers.set(
          key,
          window.setTimeout(() => {
            this.reloadTimers.delete(key)
            void this.reloadProject(key)
          }, ProjectStore.RELOAD_DEBOUNCE_MS)
        )
      }
    }
  }

  private async reloadProject(path: string): Promise<void> {
    const live = await this.projectCache.get(path)
    if (!live) return
    await this.queue(path, async () => {
      const file = this.app.vault.getAbstractFileByPath(path)
      if (!(file instanceof TFile)) {
        this.projectCache.delete(path)
        this.emitChange(path)
        return
      }
      const fresh = await this.readProject(file)
      if (!fresh) return
      this.adopt(live, fresh)
      this.emitChange(path)
    })
  }

  /** Copy a freshly read project onto the live instance every holder already has. */
  private adopt(live: Project, fresh: Project): void {
    const { taskIndex, ...fields } = fresh
    Object.assign(live, fields)
    rebuildTaskIndex(live)
    if (this.hydratedBodies.has(fresh)) this.hydratedBodies.add(live)
    else this.hydratedBodies.delete(live)
  }

  /** Serialize work on one project: saves and reloads never interleave. */
  private queue<T>(key: string, work: () => Promise<T>): Promise<T> {
    const prev = this.saveQueues.get(key) ?? Promise.resolve()
    const next = (async () => {
      await prev
      return work()
    })()
    this.saveQueues.set(
      key,
      (async () => {
        try {
          await next
        } catch {
          // swallow so the next queued item still runs after a failure
        }
      })()
    )
    return next
  }

  async ensureFolder(folderPath: string): Promise<void> {
    await ensureFolder(this.app, folderPath)
  }

  async loadProjectByPath(path: string): Promise<Project | null> {
    const file = this.app.vault.getAbstractFileByPath(normalizePath(path))
    return file instanceof TFile ? this.loadProject(file) : null
  }

  /** Concurrent callers share the one in-flight read, so a project never exists twice. */
  async loadProject(file: TFile): Promise<Project | null> {
    const live = this.projectCache.get(file.path)
    if (live) return live
    const loading = this.readProject(file)
    this.projectCache.set(file.path, loading)
    const project = await loading
    if (!project) this.projectCache.delete(file.path)
    return project
  }

  private async readProject(file: TFile): Promise<Project | null> {
    try {
      // metadataCache lets us skip the disk read; a hand-made note without a task list
      // still needs its body read for the description.
      const cached = this.app.metadataCache.getFileCache(file)?.frontmatter
      const cacheUsable = cached && cached[FRONTMATTER_KEY] === true && Array.isArray(cached.taskIds)

      let frontmatter: Record<string, unknown> | null = null
      let body = ''
      let bodyRead = false
      if (cacheUsable) {
        frontmatter = cached
      } else {
        const content = await this.app.vault.cachedRead(file)
        const parsed = parseFrontmatter(content)
        frontmatter = parsed.frontmatter
        body = parsed.body
        bodyRead = true
      }
      if (!frontmatter || frontmatter[FRONTMATTER_KEY] !== true) return null

      const project = hydrateProjectFromFrontmatter(frontmatter, body, file.path, file.basename)
      if (bodyRead) this.hydratedBodies.add(project)
      await this.adoptCustomFields(customFieldList(frontmatter.customFields))

      const taskIds = Array.isArray(frontmatter.taskIds) ? (frontmatter.taskIds as string[]) : []
      project.tasks = await this.loadTasksFromFolder(projectTaskFolder(project.filePath), taskIds, project.filePath)
      rebuildTaskIndex(project)
      this.clearDirty(project)

      return project
    } catch (e) {
      console.error(`[PM] Failed to load project ${file.path}:`, e)
      new Notice(`Project Manager: Failed to load "${file.basename}". Check console for details.`)
      return null
    }
  }

  /**
   * Custom fields an earlier version kept on the project note belong in the settings now.
   * Folding them in keeps the columns and editors for values tasks already carry; the next
   * save of the note scrubs the old key.
   */
  private async adoptCustomFields(fields: CustomFieldDef[]): Promise<void> {
    if (!fields.length) return
    const settings = this.getSettings()
    const known = new Set(settings.customFields.map((field) => field.id))
    const fresh = fields.filter((field) => !known.has(field.id))
    if (!fresh.length) return
    settings.customFields.push(...fresh)
    await this.persistSettings?.()
  }

  private async loadTasksFromFolder(folderPath: string, topLevelRefs: string[], projectPath: string): Promise<Task[]> {
    const folder = this.app.vault.getAbstractFileByPath(folderPath)
    if (!(folder instanceof TFolder)) return []

    const taskMap = new Map<string, Task>()
    const subtaskIdsMap = new Map<string, string[]>()
    const parentIdMap = new Map<string, string>()
    const archivePrefix = normalizePath(folderPath + '/Archive') + '/'

    const files: TFile[] = []
    const collect = (f: TFolder): void => {
      for (const child of f.children) {
        if (child instanceof TFile && child.extension === 'md') files.push(child)
        else if (child instanceof TFolder) collect(child)
      }
    }
    collect(folder)

    const results = await Promise.all(files.map((file) => this.loadTaskFile(file)))

    // References are wikilinks, so the notes have to be read before any of them can be
    // followed. Anything that is not a link is an id from a vault written before that.
    const idByPath = new Map<string, string>()
    for (let i = 0; i < files.length; i++) {
      const task = results[i].task
      if (task) idByPath.set(files[i].path, task.id)
    }

    for (let i = 0; i < files.length; i++) {
      const { task, subtaskIds, parentId } = results[i]
      if (task) {
        const source = files[i].path
        if (source.startsWith(archivePrefix)) {
          task.archived = true
        }
        task.dependencies = refListToIds(this.app, task.dependencies, source, idByPath)
        const subIds = refListToIds(this.app, subtaskIds, source, idByPath)
        const pid = parentId ? refToId(this.app, parentId, source, idByPath) : null
        taskMap.set(task.id, task)
        if (subIds.length) subtaskIdsMap.set(task.id, subIds)
        if (pid) parentIdMap.set(task.id, pid)
      }
    }

    for (const [taskId, sids] of subtaskIdsMap) {
      const task = taskMap.get(taskId)
      if (!task) continue
      task.subtasks = []
      for (const sid of sids) {
        const sub = taskMap.get(sid)
        if (sub) task.subtasks.push(sub)
      }
    }

    // Re-parent orphans from the parentId in their own file.
    const childIds = new Set<string>()
    for (const t of taskMap.values()) {
      for (const s of t.subtasks) childIds.add(s.id)
    }
    for (const [taskId, pid] of parentIdMap) {
      if (childIds.has(taskId)) continue
      const parent = taskMap.get(pid)
      if (!parent) continue
      const task = taskMap.get(taskId)
      if (!task) continue
      parent.subtasks.push(task)
      childIds.add(taskId)
      if (!subtaskIdsMap.has(pid)) subtaskIdsMap.set(pid, [])
      const sids = subtaskIdsMap.get(pid)
      if (sids && !sids.includes(taskId)) sids.push(taskId)
      console.warn(
        `[PM] Self-healed orphan: re-parented task "${task.title}" (${taskId}) under "${parent.title}" (${pid})`
      )
    }

    const result: Task[] = []
    const pushed = new Set<string>()
    for (const id of refListToIds(this.app, topLevelRefs, projectPath, idByPath)) {
      if (pushed.has(id)) continue
      const task = taskMap.get(id)
      if (task) {
        result.push(task)
        pushed.add(id)
      }
    }
    for (const task of taskMap.values()) {
      if (pushed.has(task.id)) continue
      if (!childIds.has(task.id)) result.push(task)
    }

    return result
  }

  async loadTaskFile(file: TFile): Promise<{ task: Task | null; subtaskIds: string[]; parentId: string | null }> {
    try {
      // metadataCache lets us skip the body read; description stays empty until
      // loadTaskBody fills it.
      const cached = this.app.metadataCache.getFileCache(file)?.frontmatter
      if (cached && cached[TASK_FRONTMATTER_KEY] === true) {
        return hydrateTaskFromFile(cached, '', file.path)
      }

      const content = await this.app.vault.cachedRead(file)
      const { frontmatter, body } = parseFrontmatter(content)
      if (!frontmatter || frontmatter[TASK_FRONTMATTER_KEY] !== true) {
        return { task: null, subtaskIds: [], parentId: null }
      }

      const result = hydrateTaskFromFile(frontmatter, body, file.path)
      this.hydratedBodies.add(result.task)
      return result
    } catch (e) {
      if (e instanceof Error && e.message.includes('ENOENT')) {
        console.warn(`[PM] Task file no longer exists, skipping: ${file.path}`)
      } else {
        console.error(`[PM] Failed to load task ${file.path}:`, e)
        new Notice(`Project Manager: Failed to load task "${file.basename}". Check console for details.`)
      }
      return { task: null, subtaskIds: [], parentId: null }
    }
  }

  /** Fill in the description from the file body. No-op once it matches disk. */
  async loadTaskBody(task: Task): Promise<void> {
    if (this.hydratedBodies.has(task)) return
    if (!task.filePath) {
      this.hydratedBodies.add(task)
      return
    }
    const file = this.app.vault.getAbstractFileByPath(task.filePath)
    if (!(file instanceof TFile)) {
      this.hydratedBodies.add(task)
      return
    }
    const content = await this.app.vault.cachedRead(file)
    const { body } = parseFrontmatter(content)
    task.description = stripAutoGeneratedContent(body)
    this.hydratedBodies.add(task)
  }

  /** Same as loadTaskBody but for the project file's body. */
  async loadProjectBody(project: Project): Promise<void> {
    if (this.hydratedBodies.has(project)) return
    const file = this.app.vault.getAbstractFileByPath(project.filePath)
    if (!(file instanceof TFile)) {
      this.hydratedBodies.add(project)
      return
    }
    const content = await this.app.vault.cachedRead(file)
    const { frontmatter, body } = parseFrontmatter(content)
    const fmDesc = frontmatter?.description
    project.description = typeof fmDesc === 'string' ? fmDesc : body.trim()
    this.hydratedBodies.add(project)
  }

  async saveProject(project: Project): Promise<void> {
    return this.queue(project.filePath, () => this.doSaveProject(project))
  }

  /** Patch-only, so the editor's stale draft can't overwrite fields it didn't change. */
  async updateProject(project: Project, patch: ProjectPatch): Promise<void> {
    const previousPath = project.filePath
    Object.assign(project, patch)
    if (patch.description !== undefined) this.hydratedBodies.add(project)
    if (patch.title !== undefined) await this.renameProjectFile(project, previousPath)
    await this.saveProject(project)
  }

  /** A title edited in the settings view renames the note; its task folder stays beside it. */
  private async renameProjectFile(project: Project, currentPath: string): Promise<void> {
    const file = this.app.vault.getAbstractFileByPath(currentPath)
    if (!(file instanceof TFile)) return
    const desiredBasename = sanitizeFileName(project.title)
    if (!desiredBasename) return
    const dir = folderOf(currentPath)
    const target = normalizePath(dir ? `${dir}/${desiredBasename}.md` : `${desiredBasename}.md`)
    if (target === currentPath || this.app.vault.getAbstractFileByPath(target)) return

    this.markSelfWrite(currentPath)
    this.markSelfWrite(target)
    await this.app.fileManager.renameFile(file, target)
    const notePath = await keepProjectStorageWithNote(this.app, currentPath, target, (p) => this.markSelfWrite(p))
    await this.rekeyProject(currentPath, notePath)
  }

  private async doSaveProject(project: Project): Promise<void> {
    // Snapshot before any await, so concurrent markDirty calls land in the next save.
    const dirty = this.dirtyTasks.get(project.filePath) ?? new Map<string, DirtyKind>()
    this.dirtyTasks.delete(project.filePath)

    try {
      project.updatedAt = new Date().toISOString()

      const dir = folderOf(project.filePath)
      if (dir) await this.ensureFolder(dir)
      const taskFolder = projectTaskFolder(project.filePath)
      await this.ensureFolder(taskFolder)

      await this.saveDirtyTasks(project, taskFolder, dirty)

      const file = this.app.vault.getAbstractFileByPath(project.filePath)
      if (file instanceof TFile) {
        this.markSelfWrite(project.filePath)
        await this.app.vault.process(file, (content) => {
          const { frontmatter, body } = parseFrontmatter(content)
          if (!this.hydratedBodies.has(project)) {
            const fmDesc = frontmatter?.description
            project.description = typeof fmDesc === 'string' ? fmDesc : body.trim()
          }
          return serializeProject(
            project,
            this.statusesFor(project),
            this.refsFor(project, project.filePath),
            foreignFrontmatter(frontmatter, PROJECT_FRONTMATTER_KEYS)
          )
        })
        this.hydratedBodies.add(project)
      } else {
        const content = serializeProject(project, this.statusesFor(project), this.refsFor(project, project.filePath))
        this.markSelfWrite(project.filePath)
        await this.app.vault.create(project.filePath, content)
        this.hydratedBodies.add(project)
      }
      // A project saved before it was ever loaded (creation, migration) becomes the
      // live instance, but a save never replaces an instance others already hold.
      if (!this.projectCache.has(project.filePath)) {
        this.projectCache.set(project.filePath, Promise.resolve(project))
      }
      this.emitChange(project.filePath)
    } catch (e) {
      // Merge the snapshot back so the next save retries.
      for (const [id, kind] of dirty) this.markDirty(project, [id], kind)
      if (e instanceof TaskFileNameConflictError) throw e
      console.error(`[PM] Failed to save project "${project.title}":`, e)
      new Notice(`Project Manager: Failed to save "${project.title}". Check console for details.`)
      throw e
    }
  }

  private async saveDirtyTasks(project: Project, folder: string, dirty: Map<string, DirtyKind>): Promise<void> {
    // Safety net: a task never written to disk gets a file even if nothing marked it.
    for (const [id, entry] of project.taskIndex) {
      if (!entry.task.filePath && !dirty.has(id)) dirty.set(id, 'full')
    }
    if (dirty.size === 0) return

    const jobs: { task: Task; parentTask: Task | null; folder: string; kind: DirtyKind }[] = []
    const targetPaths = new Set<string>()
    let hasArchived = false
    for (const [id, kind] of dirty) {
      const entry = project.taskIndex.get(id)
      if (!entry) continue // deleted after being marked dirty
      const { task, parentId } = entry
      const targetFolder = task.archived ? normalizePath(folder + '/Archive') : folder
      if (task.archived) hasArchived = true
      // Two dirty tasks resolving to one file would race below into a generic
      // create error; catching it here keeps the typed one.
      const path = normalizePath(taskFilePath(task.title, targetFolder))
      if (targetPaths.has(path)) throw new TaskFileNameConflictError(path)
      targetPaths.add(path)
      jobs.push({ task, parentTask: parentId ? findTaskById(project, parentId) : null, folder: targetFolder, kind })
    }
    if (hasArchived) await this.ensureFolder(normalizePath(folder + '/Archive'))

    const errors: Error[] = []
    const batchSize = 16
    for (let i = 0; i < jobs.length; i += batchSize) {
      const results = await Promise.allSettled(
        jobs.slice(i, i + batchSize).map((j) => this.saveTaskFile(j.task, project, j.parentTask, j.folder, j.kind))
      )
      for (const r of results) {
        if (r.status === 'rejected') errors.push(r.reason instanceof Error ? r.reason : new Error(String(r.reason)))
      }
    }
    if (errors.length) {
      if (errors.length === 1 && errors[0] instanceof TaskFileNameConflictError) throw errors[0]
      throw new Error(`Failed to save ${errors.length} task(s): ${errors.map((e) => e.message).join('; ')}`)
    }
  }

  private async saveTaskFile(
    task: Task,
    project: Project,
    parentTask: Task | null,
    folder: string,
    kind: DirtyKind
  ): Promise<void> {
    const previousPath = task.filePath
    const filePath = normalizePath(taskFilePath(task.title, folder))
    const renamed = previousPath !== undefined && previousPath !== filePath

    try {
      if (kind === 'fm' && previousPath && !renamed) {
        const existing = this.app.vault.getAbstractFileByPath(filePath)
        if (existing instanceof TFile) {
          this.markSelfWrite(filePath)
          const next = buildTaskFrontmatter(task, project, parentTask, this.refsFor(project, filePath))
          await this.app.fileManager.processFrontMatter(existing, (fm: Record<string, unknown>) => {
            const foreign = foreignFrontmatter(fm, TASK_FRONTMATTER_KEYS)
            for (const k of Object.keys(fm)) Reflect.deleteProperty(fm, k)
            Object.assign(fm, next, foreign)
          })
          return
        }
        // File is missing; fall through and recreate it.
      }

      const existing = this.app.vault.getAbstractFileByPath(filePath)
      if (existing instanceof TFile && existing.path !== previousPath) {
        throw new TaskFileNameConflictError(filePath)
      }

      if (existing instanceof TFile) {
        this.markSelfWrite(filePath)
        await this.app.vault.process(existing, (content) => {
          const { frontmatter, body } = parseFrontmatter(content)
          if (!this.hydratedBodies.has(task)) {
            task.description = stripAutoGeneratedContent(body)
          }
          return serializeTask(
            task,
            project,
            parentTask,
            this.statusesFor(project),
            this.refsFor(project, filePath),
            foreignFrontmatter(frontmatter, TASK_FRONTMATTER_KEYS)
          )
        })
      } else {
        let foreign: Record<string, unknown> = {}
        const oldFile = previousPath ? this.app.vault.getAbstractFileByPath(previousPath) : null
        if (oldFile instanceof TFile) {
          const { frontmatter, body } = parseFrontmatter(await this.app.vault.cachedRead(oldFile))
          if (!this.hydratedBodies.has(task)) task.description = stripAutoGeneratedContent(body)
          foreign = foreignFrontmatter(frontmatter, TASK_FRONTMATTER_KEYS)
        }
        const content = serializeTask(
          task,
          project,
          parentTask,
          this.statusesFor(project),
          this.refsFor(project, filePath),
          foreign
        )
        this.markSelfWrite(filePath)
        await this.app.vault.create(filePath, content)
      }
      task.filePath = filePath
      this.hydratedBodies.add(task)

      if (renamed && previousPath) {
        const oldFile = this.app.vault.getAbstractFileByPath(previousPath)
        if (oldFile instanceof TFile) {
          this.markSelfWrite(previousPath)
          await this.app.fileManager.trashFile(oldFile)
        }
        // Keep the task's attachment folder with the renamed note.
        this.markSelfWrite(this.taskFolder(previousPath))
        this.markSelfWrite(this.taskFolder(filePath))
        await moveTaskAttachmentFolder(this.app, previousPath, filePath)
      }
    } catch (e) {
      if (!(e instanceof TaskFileNameConflictError)) {
        console.error(`[PM] Failed to save task "${task.title}" (${task.id}):`, e)
      }
      throw e
    }
  }

  /** Pre-flight check so callers can surface the conflict inline instead of on save. */
  findTaskFileConflict(project: Project, task: Task): TaskFileNameConflictError | null {
    const baseFolder = projectTaskFolder(project.filePath)
    const folder = task.archived ? normalizePath(baseFolder + '/Archive') : baseFolder
    const desired = normalizePath(taskFilePath(task.title, folder))
    if (desired === task.filePath) return null
    const existing = this.app.vault.getAbstractFileByPath(desired)
    return existing instanceof TFile ? new TaskFileNameConflictError(desired) : null
  }

  async createProject(title: string, folder: string, patch?: ProjectPatch): Promise<Project> {
    const project = makeProject(title, projectFilePath(title, folder))
    if (patch) Object.assign(project, patch)
    await this.saveProject(project)
    return project
  }

  async insertTask(project: Project, task: Task, parentId: string | null = null): Promise<void> {
    if (!task.completed && isTerminalStatus(task.status, this.statusesFor(project))) {
      task.completed = today().toString()
    }
    this.hydratedBodies.add(task)
    addTaskToTree(project.tasks, task, parentId)
    indexAddSubtree(project, task, parentId)
    this.markDirty(project, [task.id], 'full')
    if (parentId) this.markDirty(project, [parentId], 'full')
    await this.saveProject(project)
  }

  /**
   * Turn a vault note into a top-level task file; its body becomes the description.
   * The project file isn't rewritten: the next load picks the task up as an orphan.
   */
  async importNoteAsTask(project: Project, file: TFile, opts: ImportNoteOptions): Promise<'imported' | 'skipped'> {
    const content = await this.app.vault.read(file)
    const { frontmatter, body } = parseFrontmatter(content)
    if (frontmatter?.[TASK_FRONTMATTER_KEY] === true) return 'skipped'

    const task = makeTask({
      title: file.basename,
      description: body,
      status: opts.status,
      priority: opts.priority
    })
    const folder = projectTaskFolder(project.filePath)
    await this.ensureFolder(folder)
    const newFilePath = taskFilePath(task.title, folder)
    const newContent = serializeTask(
      task,
      project,
      null,
      this.statusesFor(project),
      this.refsFor(project, newFilePath),
      foreignFrontmatter(frontmatter, TASK_FRONTMATTER_KEYS)
    )

    if (opts.handling === 'move') {
      await this.app.fileManager.renameFile(file, newFilePath)
      const moved = this.app.vault.getAbstractFileByPath(newFilePath)
      if (moved instanceof TFile) {
        await this.app.vault.process(moved, () => newContent)
      }
    } else {
      await this.app.vault.create(newFilePath, newContent)
    }
    return 'imported'
  }

  /**
   * Persist a converted task forest as task files. 'move' turns each source note into
   * the task file, 'copy' leaves sources untouched. The project file isn't rewritten:
   * the next load recovers order and parenting from the written parentId/subtaskIds.
   */
  async importTaskForest(
    project: Project,
    roots: Task[],
    sources: Map<string, TFile>,
    handling: 'move' | 'copy'
  ): Promise<number> {
    const baseFolder = projectTaskFolder(project.filePath)
    await this.ensureFolder(baseFolder)
    let imported = 0

    const writeNode = async (task: Task, parent: Task | null): Promise<void> => {
      const folder = task.archived ? normalizePath(baseFolder + '/Archive') : baseFolder
      if (task.archived) await this.ensureFolder(folder)
      const source = sources.get(task.id)
      let foreign: Record<string, unknown> = {}
      if (source) {
        const { frontmatter, body } = parseFrontmatter(await this.app.vault.read(source))
        task.description = body
        foreign = foreignFrontmatter(frontmatter, TASK_FRONTMATTER_KEYS)
      }
      const desired = taskFilePath(task.title, folder)
      const dest = this.uniqueChildPath(folder, desired.slice(desired.lastIndexOf('/') + 1))
      const content = serializeTask(
        task,
        project,
        parent,
        this.statusesFor(project),
        this.refsFor(project, dest),
        foreign
      )
      if (handling === 'move' && source) {
        await this.app.fileManager.renameFile(source, dest)
        const moved = this.app.vault.getAbstractFileByPath(dest)
        if (moved instanceof TFile) {
          await this.app.vault.process(moved, () => content)
        }
      } else {
        await this.app.vault.create(dest, content)
      }
      imported++
      for (const child of task.subtasks) {
        await writeNode(child, task)
      }
    }

    for (const root of roots) {
      await writeNode(root, null)
    }
    return imported
  }

  async duplicateTask(project: Project, sourceId: string, includeSubtasks: boolean): Promise<Task | null> {
    const source = findTaskById(project, sourceId)
    if (!source) return null
    const copy = cloneTaskSubtree(source, includeSubtasks)
    // Filenames come from the title slug within one flat folder, so a clone keeping
    // the source title would write over the original. Reserve a free "(copy)" title
    // for every node, checking the clones we're adding so siblings don't collide.
    const baseFolder = projectTaskFolder(project.filePath)
    const claimed = new Set<string>()
    const usedTitles = new Set(flattenTasks(project.tasks).map((f) => f.task.title))
    const claimName = (task: Task): void => {
      const folder = task.archived ? normalizePath(baseFolder + '/Archive') : baseFolder
      this.assignCopyName(task, folder, usedTitles, claimed)
    }
    // A clone has no file yet, and its in-memory description must be written verbatim.
    claimName(copy)
    this.hydratedBodies.add(copy)
    for (const ft of flattenTasks(copy.subtasks)) {
      claimName(ft.task)
      this.hydratedBodies.add(ft.task)
    }
    const parentId = findParentId(project, sourceId)
    addTaskToTree(project.tasks, copy, parentId)
    moveTaskInTree(project.tasks, copy.id, sourceId, 'after')
    indexAddSubtree(project, copy, parentId)
    this.markSubtreeDirty(project, copy.id, 'full')
    if (parentId) this.markDirty(project, [parentId], 'full')
    await this.saveProject(project)
    return copy
  }

  private assignCopyName(task: Task, folder: string, usedTitles: Set<string>, claimed: Set<string>): void {
    const base = task.title.replace(/(?: \(copy(?: \d+)?\))+$/, '')
    for (let n = 1; ; n++) {
      const suffix = n === 1 ? ' (copy)' : ` (copy ${n})`
      const room = TASK_SLUG_MAX_LENGTH - suffix.length
      const title = (base.length > room ? base.slice(0, room).trimEnd() : base) + suffix
      const path = normalizePath(taskFilePath(title, folder))
      if (
        !usedTitles.has(title) &&
        !claimed.has(path) &&
        !(this.app.vault.getAbstractFileByPath(path) instanceof TFile)
      ) {
        usedTitles.add(title)
        claimed.add(path)
        task.title = title
        return
      }
    }
  }

  async moveTask(project: Project, taskId: string, newParentId: string | null): Promise<void> {
    const task = findTaskById(project, taskId)
    if (!task) return
    const oldParentId = findParentId(project, taskId)
    deleteTaskFromTree(project.tasks, taskId)
    addTaskToTree(project.tasks, task, newParentId)
    indexSetParent(project, taskId, newParentId)
    // The moved task's Parent link and both parents' Subtasks lists live in the body.
    this.markDirty(project, [taskId], 'full')
    if (oldParentId) this.markDirty(project, [oldParentId], 'full')
    if (newParentId) this.markDirty(project, [newParentId], 'full')
    await this.saveProject(project)
  }

  async moveTasks(project: Project, taskIds: string[], newParentId: string | null): Promise<void> {
    for (const id of taskIds) {
      const task = findTaskById(project, id)
      if (!task) continue
      const oldParentId = findParentId(project, id)
      deleteTaskFromTree(project.tasks, id)
      addTaskToTree(project.tasks, task, newParentId)
      indexSetParent(project, id, newParentId)
      this.markDirty(project, [id], 'full')
      if (oldParentId) this.markDirty(project, [oldParentId], 'full')
    }
    if (newParentId) this.markDirty(project, [newParentId], 'full')
    await this.saveProject(project)
  }

  /**
   * Stamp or clear `completed` when a status crosses the complete boundary, mutating
   * `patch` so it lands in the same save. An explicit `completed` in the patch wins.
   */
  private stampCompletion(project: Project, task: Task, patch: Partial<Task>): void {
    if (patch.status === undefined) return
    if (patch.completed !== undefined && patch.completed !== task.completed) return
    const statuses = this.statusesFor(project)
    const wasComplete = isTerminalStatus(task.status, statuses)
    const nowComplete = isTerminalStatus(patch.status, statuses)
    if (nowComplete && !wasComplete) patch.completed = today().toString()
    else if (!nowComplete && wasComplete) patch.completed = ''
  }

  /** Call between `stampCompletion` and the patch reaching the tree, while `task` still holds its old value. */
  private completionMoved(task: Task, patch: Partial<Task>): boolean {
    return patch.completed !== undefined && patch.completed !== task.completed
  }

  private async scheduleAfterEarlyFinish(project: Project, taskIds: string[]): Promise<void> {
    if (taskIds.length === 0 || !this.configFor(project).pullForwardOnEarlyFinish) return
    for (const id of taskIds) await this.scheduleAfterChange(project, id)
  }

  async updateTask(project: Project, taskId: string, patch: Partial<Task>): Promise<void> {
    const task = findTaskById(project, taskId)
    const oldTitle = task?.title
    if (task) this.stampCompletion(project, task, patch)
    const completionMoved = task !== null && this.completionMoved(task, patch)
    // The editor saves the whole task, so snapshot the subtree to diff against.
    const oldSubtree = task && patch.subtasks !== undefined ? flattenTasks(task.subtasks).map((f) => f.task) : []
    updateTaskInTree(project.tasks, taskId, patch)
    const titleChanged = task && patch.title !== undefined && patch.title !== oldTitle
    // A title change renames the file, forcing saveTaskFile's rename branch.
    const kind: DirtyKind = patchNeedsBodyRewrite(patch) || titleChanged ? 'full' : 'fm'
    this.markDirty(project, [taskId], kind)
    if (task && patch.description !== undefined) this.hydratedBodies.add(task)
    if (task && patch.subtasks !== undefined) {
      await this.reconcileSubtasks(project, task, oldSubtree)
    } else if (task && titleChanged) {
      // The rename breaks direct children's Parent link.
      for (const sub of task.subtasks) this.markDirty(project, [sub.id], 'full')
    }
    await this.saveProject(project)
    if (completionMoved) await this.scheduleAfterEarlyFinish(project, [taskId])
  }

  /**
   * Make the index and the on-disk files match a subtree the editor saved wholesale:
   * re-point the index, mark new/renamed/restatused subtasks for a write, and trash
   * files for the ones removed. Unchanged subtasks aren't rewritten.
   */
  private async reconcileSubtasks(project: Project, parent: Task, oldSubtree: Task[]): Promise<void> {
    indexAddSubtree(project, parent, findParentId(project, parent.id))

    const old = new Map(oldSubtree.map((t) => [t.id, t]))
    const liveIds = new Set<string>()
    for (const { task } of flattenTasks(parent.subtasks)) {
      liveIds.add(task.id)
      const prev = old.get(task.id)
      if (!prev) {
        this.hydratedBodies.add(task)
        this.markDirty(project, [task.id], 'full')
      } else if (prev.title !== task.title) {
        this.markDirty(project, [task.id], 'full')
      } else if (prev.status !== task.status || prev.completed !== task.completed || prev.progress !== task.progress) {
        this.markDirty(project, [task.id], 'fm')
      }
    }

    const folder = projectTaskFolder(project.filePath)
    for (const removed of oldSubtree) {
      if (liveIds.has(removed.id)) continue
      project.taskIndex.delete(removed.id)
      // The snapshot is flat and already lists every descendant.
      if (removed.filePath) await this.deleteTaskFiles({ ...removed, subtasks: [] }, folder)
    }
  }

  /** Patch several tasks in one save. A `patch` function returning null skips its task. */
  async updateTasks(
    project: Project,
    taskIds: string[],
    patch: Partial<Task> | ((task: Task) => Partial<Task> | null)
  ): Promise<void> {
    const completionMovedIds: string[] = []
    for (const id of taskIds) {
      const task = findTaskById(project, id)
      if (!task) continue
      const raw = typeof patch === 'function' ? patch(task) : patch
      if (!raw) continue
      // Copy before stamping so one task's completion date doesn't bleed onto the next.
      const p = { ...raw }
      this.stampCompletion(project, task, p)
      if (this.completionMoved(task, p)) completionMovedIds.push(id)
      const oldTitle = task.title
      updateTaskInTree(project.tasks, id, p)
      const titleChanged = p.title !== undefined && p.title !== oldTitle
      const kind: DirtyKind = patchNeedsBodyRewrite(p) || titleChanged ? 'full' : 'fm'
      this.markDirty(project, [id], kind)
      if (p.description !== undefined) this.hydratedBodies.add(task)
      if (titleChanged) {
        for (const sub of task.subtasks) this.markDirty(project, [sub.id], 'full')
      }
    }
    await this.saveProject(project)
    await this.scheduleAfterEarlyFinish(project, completionMovedIds)
  }

  /** Sibling order lives in the parent's subtaskIds, so only the parent is rewritten. */
  async reorderTask(project: Project, taskId: string, targetId: string, position: 'before' | 'after'): Promise<void> {
    if (!moveTaskInTree(project.tasks, taskId, targetId, position)) return
    const parentId = findParentId(project, targetId)
    if (parentId) this.markDirty(project, [parentId], 'full')
    await this.saveProject(project)
  }

  async deleteTasks(project: Project, taskIds: string[]): Promise<void> {
    const folder = projectTaskFolder(project.filePath)
    const dirtyParents = new Set<string>()
    for (const id of taskIds) {
      const parentId = findParentId(project, id)
      if (parentId) dirtyParents.add(parentId)
      const task = findTaskById(project, id)
      if (task) {
        await this.deleteTaskFiles(task, folder)
        indexRemoveSubtree(project, task)
      }
      deleteTaskFromTree(project.tasks, id)
    }
    // The parents' Subtasks lists shrink.
    if (dirtyParents.size) this.markDirty(project, dirtyParents, 'full')
    await this.saveProject(project)
  }

  async archiveTask(project: Project, taskId: string): Promise<void> {
    await doArchiveTask(this.app, project, taskId, (path) => this.markSelfWrite(path))
    await this.saveProject(project)
  }

  /** Archives several tasks, and their subtrees, in one save. */
  async archiveTasks(project: Project, taskIds: string[]): Promise<void> {
    for (const taskId of taskIds) {
      await doArchiveTask(this.app, project, taskId, (path) => this.markSelfWrite(path))
    }
    await this.saveProject(project)
  }

  async unarchiveTask(project: Project, taskId: string): Promise<void> {
    await doUnarchiveTask(this.app, project, taskId, (path) => this.markSelfWrite(path))
    await this.saveProject(project)
  }

  async deleteTask(project: Project, taskId: string): Promise<void> {
    const parentId = findParentId(project, taskId)
    const task = findTaskById(project, taskId)
    if (task) {
      await this.deleteTaskFiles(task, projectTaskFolder(project.filePath))
      indexRemoveSubtree(project, task)
    }
    deleteTaskFromTree(project.tasks, taskId)
    // The parent's Subtasks list shrinks.
    if (parentId) this.markDirty(project, [parentId], 'full')
    await this.saveProject(project)
  }

  private async deleteTaskFiles(task: Task, folder: string): Promise<void> {
    for (const sub of task.subtasks) {
      await this.deleteTaskFiles(sub, folder)
    }
    if (task.filePath) {
      const file = this.app.vault.getAbstractFileByPath(task.filePath)
      if (file instanceof TFile) {
        this.markSelfWrite(task.filePath)
        await this.app.fileManager.trashFile(file)
      }
      const taskDir = this.app.vault.getAbstractFileByPath(this.taskFolder(task.filePath))
      if (taskDir instanceof TFolder) {
        await this.deleteFolderRecursive(taskDir)
      }
    }
  }

  /** A task's own folder, holding its attachments. */
  private taskFolder(taskFilePath: string): string {
    return taskFilePath.replace(/\.md$/, '')
  }

  /** Keeps a pasted or dropped file with the task, not in the vault-wide default folder. */
  async saveTaskAttachment(project: Project, task: Task, fileName: string, data: ArrayBuffer): Promise<TFile> {
    const taskPath = task.filePath ?? taskFilePath(task.title, projectTaskFolder(project.filePath))
    const dir = normalizePath(`${this.taskFolder(taskPath)}/attachments`)
    this.markSelfWrite(this.taskFolder(taskPath))
    this.markSelfWrite(dir)
    await this.ensureFolder(dir)
    const path = this.uniqueChildPath(dir, fileName)
    this.markSelfWrite(path)
    return this.app.vault.createBinary(path, data)
  }

  private uniqueChildPath(folder: string, fileName: string): string {
    const dot = fileName.lastIndexOf('.')
    const base = dot > 0 ? fileName.slice(0, dot) : fileName
    const ext = dot > 0 ? fileName.slice(dot) : ''
    let candidate = normalizePath(`${folder}/${base}${ext}`)
    for (let n = 1; this.app.vault.getAbstractFileByPath(candidate); n++) {
      candidate = normalizePath(`${folder}/${base} ${n}${ext}`)
    }
    return candidate
  }

  /**
   * The task folder and the note go; the folder around them only when nothing else is
   * left in it, so a people folder or any other note beside the project survives.
   */
  async deleteProject(project: Project): Promise<void> {
    const tasks = this.app.vault.getAbstractFileByPath(projectTaskFolder(project.filePath))
    if (tasks instanceof TFolder) {
      this.markSelfWrite(project.filePath)
      await this.deleteFolderRecursive(tasks)
    }
    const file = this.app.vault.getAbstractFileByPath(project.filePath)
    if (file instanceof TFile) {
      this.markSelfWrite(project.filePath)
      await this.app.fileManager.trashFile(file)
    }
    const dir = folderOf(project.filePath)
    const folder = dir ? this.app.vault.getAbstractFileByPath(dir) : null
    if (folder instanceof TFolder && folder.children.length === 0) await this.app.fileManager.trashFile(folder)
    this.clearDirty(project)
    this.saveQueues.delete(project.filePath)
    this.projectCache.delete(project.filePath)
    this.emitChange(project.filePath)
  }

  private async deleteFolderRecursive(folder: TFolder): Promise<void> {
    for (const child of folder.children.slice()) {
      if (child instanceof TFile) {
        this.markSelfWrite(child.path)
        await this.app.fileManager.trashFile(child)
      } else if (child instanceof TFolder) {
        await this.deleteFolderRecursive(child)
      }
    }
    await this.app.fileManager.trashFile(folder)
  }

  /** Apply dependency-based scheduling and save, returning the number of tasks adjusted. */
  async scheduleAfterChange(project: Project, changedTaskId?: string): Promise<number> {
    const config = this.configFor(project)
    if (!config.autoSchedule) return 0
    const { patches } = computeSchedule(
      project.tasks,
      changedTaskId === undefined ? undefined : [changedTaskId],
      config.statuses,
      config.pullForwardOnEarlyFinish
    )
    if (patches.length === 0) return 0

    for (const p of patches) {
      updateTaskInTree(project.tasks, p.taskId, { start: p.start, due: p.due })
      this.markDirty(project, [p.taskId], 'fm')
    }
    await this.saveProject(project)
    return patches.length
  }
}
